baseURL: 'https://blog.abdelfattah.site'
title: AM Garden
theme: PaperMod
paginate: 5


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Home
                  url: https://abdelfattah.site/
                  weight: 5
                - name: Garden
                  url: garden
                  weight: 10
                - name: Search
                  url: search/
                  weight: 15
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors

    homeInfoParams:
        Title: "AM Garden"
        Content: >
            Hello there, I am Abdelfattah an Engineer, Web Developer, Designer, Researcher, Instructor, Entrepreneur and an overall curious person.



    socialIcons:
        - name: github
          url: "https://github.com/abdelfattahmsa"
        - name: linkedin
          url: "https://www.linkedin.com/in/abdelfattahmsa/"
        - name: twitter
          url: "https://twitter.com/abdelfattah_msa"
        - name: behance
        url: "https://www.behance.net/abdelfattahmsa"
        - name: facebook
        url: "https://www.facebook.com/abdelfattah.msa"
        - name: researchgate
        url: "https://www.researchgate.net/profile/Abdelfattah_Ms_Aboalfoutoh"
        
