baseURL = 'http://hugo-quickstart-template.netlify.com'
title = 'Abdelfattahs Digital Garden'
theme = 'PaperMod'
Displays a Scroll-to-Top button in right-bottom corner
languages =
    en =
        languageName = 'English'
